[project]
name = "envman"
version = "0.1.0"
dependencies = [
    "click",
    "cryptography",
    "keyring",
]

[project.scripts]
envman = "envman:cli"

[tool.uv]
package = true

[dependency-groups]
dev = [
    "pyinstaller>=6.17.0",
]
